#version: '3.4'
services:
  main:
    # Makefile fills PROJECT_NAME to current directory name.
    # add UID to allow multiple users run this in parallel
    #container_name: ${PROJECT_NAME}_${HOST_UID:-4000}
    build:
      context: .
      # Build for current user.
      target: user
      dockerfile: Dockerfile

